import jsPDF from "jspdf";
import { Product } from "../../types/Product";

export const drawCoverPage = (
  doc: jsPDF,
  product: Product
): void => {
  const pageWidth =
    doc.internal.pageSize.getWidth();

 

  // HERO AREA

  

 doc.setFontSize(30);

doc.text(
  "PANASONIC",
  20,
  50
);

doc.setFontSize(18);

doc.text(
  "LED DISPLAY CONFIGURATION REPORT",
  20,
  70
);

doc.setDrawColor(180);

doc.line(
  20,
  80,
  190,
  80
);

doc.setFontSize(12);

let y = 100;

doc.text(
  `Model : ${product.model}`,
  20,
  y
);

y += 12;

doc.text(
  `Pixel Pitch : ${product.pitch} mm`,
  20,
  y
);

y += 12;

doc.text(
  `Brightness : ${product.brightness} nits`,
  20,
  y
);

y += 12;

doc.text(
  `Generated : ${new Date().toLocaleDateString()}`,
  20,
  y
);

doc.line(
  20,
  y + 20,
  190,
  y + 20
);

doc.setFontSize(10);

doc.text(
  "Generated by Panasonic LED Configurator",
  20,
  270
);

doc.text(
  new Date().toLocaleDateString(),
  160,
  270
);}