import jsPDF from "jspdf";
import { Product } from "../../types/Product";

interface ProposalInfo {
  projectName: string;
  customerName: string;
  companyName: string;
  email: string;
}

export const drawProposalSummaryPage = (
  doc: jsPDF,
  product: Product,
  proposalInfo: ProposalInfo,
  proposalId: string
): void => {

  doc.setFont("helvetica", "bold");
  doc.setFontSize(24);

  doc.text(
    "LED DISPLAY PROPOSAL",
    20,
    30
  );

  doc.setDrawColor(180);

  doc.line(
    20,
    40,
    190,
    40
  );

  doc.setFontSize(18);

  doc.text(
    "Project Information",
    20,
    60
  );

  doc.setFont(
    "helvetica",
    "normal"
  );

  doc.setFontSize(12);

  let y = 80;

  doc.text(
    `Proposal ID: ${proposalId}`,
    20,
    y
  );

  y += 12;

  doc.text(
    `Project Name: ${proposalInfo.projectName}`,
    20,
    y
  );

  y += 12;

  doc.text(
    `Customer Name: ${proposalInfo.customerName}`,
    20,
    y
  );

  y += 12;

  doc.text(
    `Company Name: ${proposalInfo.companyName}`,
    20,
    y
  );

  y += 12;

  doc.text(
    `Email: ${proposalInfo.email}`,
    20,
    y
  );

  y += 12;

  doc.text(
    `Generated On: ${new Date().toLocaleDateString()}`,
    20,
    y
  );

  y += 25;

  doc.setFont(
    "helvetica",
    "bold"
  );

  doc.setFontSize(18);

  doc.text(
    "Selected Product",
    20,
    y
  );

  y += 20;

  doc.setFont(
    "helvetica",
    "normal"
  );

  doc.setFontSize(12);

  doc.text(
    `Model: ${product.model}`,
    20,
    y
  );

  y += 12;

  doc.text(
    `Pixel Pitch: ${product.pitch} mm`,
    20,
    y
  );

  y += 12;

  doc.text(
    `Brightness: ${product.brightness} nits`,
    20,
    y
  );

  doc.setFontSize(10);

  doc.text(
    "Generated by Panasonic LED Configurator",
    20,
    280
  );
};