import { ConfigurationResult } from "../../types/ConfigurationResult";
import { Product } from "../../types/Product";

interface ResultsPanelProps {
  result: ConfigurationResult | null;
  selectedProduct: Product | null;
  // ADDED: Unit configuration matching master engine state
  unit: "mtr" | "ft";
}

export const ResultsPanel = ({
  result,
  selectedProduct,
  unit,
}: ResultsPanelProps) => {
  if (!result || !selectedProduct) return null;

  const METERS_TO_FEET = 3.28084;
  const SQ_METERS_TO_SQ_FEET = 10.7639;

  // Calculate base metric values
  const baseOptimalDistance = selectedProduct.pitch * 1.5;
  const baseArea = result.totalArea;
  const baseWidth = result.actualWidth;
  const baseHeight = result.actualHeight;

  // Apply conditional conversion and format text strings
  const viewingDistanceText = (unit === "mtr" ? baseOptimalDistance : baseOptimalDistance * METERS_TO_FEET).toFixed(1);
  const areaText = (unit === "mtr" ? baseArea : baseArea * SQ_METERS_TO_SQ_FEET).toFixed(2);
  const actualWidthText = (unit === "mtr" ? baseWidth : baseWidth * METERS_TO_FEET).toFixed(2);
  const actualHeightText = (unit === "mtr" ? baseHeight : baseHeight * METERS_TO_FEET).toFixed(2);

  const maxHeatBTU = result.maximumHeatBTU ?? (result.maximumPower * 3.412142);
  const avgHeatBTU = result.averageHeatBTU ?? (result.averagePower * 3.412142);

  return (
    <div className="results-panel">
      <div className="results-panel-header">
        <h2>Engineering Summary</h2>
        <p className="results-subtitle">
          Generated by Panasonic PitchLine.
        </p>
      </div>

      <div className="metrics-rows-container">
        {/* ROW 1: VISUAL PERFORMANCE */}
        <div className="metrics-row-group">
          <div className="metrics-row-title">
            <span>Visual Performance</span>
          </div>
          <div className="metrics-row-grid">
            <div className="premium-metric-card">
              <span className="metric-label">Resolution</span>
              <span className="metric-value">
                {result.resolutionW} × {result.resolutionH}
              </span>
            </div>
            <div className="premium-metric-card">
              <span className="metric-label">Display Area</span>
              <span className="metric-value">
                {areaText} {unit === "mtr" ? "mtr²" : "ft²"}
              </span>
            </div>
            <div className="premium-metric-card">
              <span className="metric-label">Brightness</span>
              <span className="metric-value">
                {selectedProduct.brightness} nits
              </span>
            </div>
            <div className="premium-metric-card">
              <span className="metric-label">Pixel Pitch</span>
              <span className="metric-value">
                {selectedProduct.pitch} mm
              </span>
            </div>
            <div className="premium-metric-card distance-highlight">
              <span className="metric-label">Optimal Distance</span>
              <span className="metric-value">
                {viewingDistanceText} {unit}
              </span>
            </div>
          </div>
        </div>

        {/* ROW 2: POWER & INFRASTRUCTURE */}
        <div className="metrics-row-group">
          <div className="metrics-row-title">
            <span>Power & Infrastructure</span>
          </div>
          <div className="metrics-row-grid">
            <div className="premium-metric-card">
              <span className="metric-label">Maximum Power</span>
              <span className="metric-value">
                {Math.round(result.maximumPower)} W
              </span>
            </div>

            <div className="premium-metric-card">
              <span className="metric-label">Average Power</span>
              <span className="metric-value">
                {Math.round(result.averagePower)} W
              </span>
            </div>

            <div className="premium-metric-card">
              <span className="metric-label">Max Heat Dissipation</span>
              <span className="metric-value">
                {Math.round(maxHeatBTU)} <small>BTU/h</small>
              </span>
            </div>

            <div className="premium-metric-card">
              <span className="metric-label">Avg Heat Dissipation</span>
              <span className="metric-value">
                {Math.round(avgHeatBTU)} <small>BTU/h</small>
              </span>
            </div>
          </div>
        </div>

        {/* ROW 3: PHYSICAL SPECS */}
        <div className="metrics-row-group">
          <div className="metrics-row-title">
            <span>Physical Specs</span>
          </div>
          <div className="metrics-row-grid physical-six-columns">
            <div className="premium-metric-card">
              <span className="metric-label">Total Cabinets</span>
              <span className="metric-value">{result.totalCabinets}</span>
            </div>
            <div className="premium-metric-card">
              <span className="metric-label">Actual Width</span>
              <span className="metric-value">
                {actualWidthText} {unit}
              </span>
            </div>
            <div className="premium-metric-card">
              <span className="metric-label">Actual Height</span>
              <span className="metric-value">
                {actualHeightText} {unit}
              </span>
            </div>
            <div className="premium-metric-card">
              <span className="metric-label">Total Modules</span>
              <span className="metric-value">{result.totalModules}</span>
            </div>
            <div className="premium-metric-card">
              <span className="metric-label">Cabinets Wide</span>
              <span className="metric-value">{result.cabinetsW}</span>
            </div>
            <div className="premium-metric-card">
              <span className="metric-label">Cabinets High</span>
              <span className="metric-value">{result.cabinetsH}</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};